use clap::{ArgMatches};
use cryptoki::object::AttributeType;

pub const ALL_ATTRS: [AttributeType; 77] = [
    AttributeType::AcIssuer,
    AttributeType::AllowedMechanisms,
    AttributeType::AlwaysAuthenticate,
    AttributeType::AlwaysSensitive,
    AttributeType::Application,
    AttributeType::AttrTypes,
    AttributeType::Base,
    AttributeType::CertificateType,
    AttributeType::CheckValue,
    AttributeType::Class,
    AttributeType::Coefficient,
    AttributeType::Copyable,
    AttributeType::Decapsulate,
    AttributeType::Decrypt,
    AttributeType::Derive,
    AttributeType::Destroyable,
    AttributeType::EcParams,
    AttributeType::EcPoint,
    AttributeType::Encapsulate,
    AttributeType::Encrypt,
    AttributeType::EndDate,
    AttributeType::Exponent1,
    AttributeType::Exponent2,
    AttributeType::Extractable,
    AttributeType::HashOfIssuerPublicKey,
    AttributeType::HashOfSubjectPublicKey,
    AttributeType::Id,
    AttributeType::Issuer,
    AttributeType::KeyGenMechanism,
    AttributeType::KeyType,
    AttributeType::Label,
    AttributeType::Local,
    AttributeType::Modifiable,
    AttributeType::Modulus,
    AttributeType::ModulusBits,
    AttributeType::NeverExtractable,
    AttributeType::ObjectId,
    AttributeType::ObjectValidationFlags,
    AttributeType::Owner,
    AttributeType::ParameterSet,
    AttributeType::Prime,
    AttributeType::Prime1,
    AttributeType::Prime2,
    AttributeType::Private,
    AttributeType::PrivateExponent,
    AttributeType::PublicExponent,
    AttributeType::PublicKeyInfo,
    AttributeType::ProfileId,
    AttributeType::Seed,
    AttributeType::Sensitive,
    AttributeType::SerialNumber,
    AttributeType::Sign,
    AttributeType::SignRecover,
    AttributeType::StartDate,
    AttributeType::Subject,
    AttributeType::Token,
    AttributeType::Trusted,
    AttributeType::UniqueId,
    AttributeType::Unwrap,
    AttributeType::Url,
    AttributeType::ValidationType,
    AttributeType::ValidationVersion,
    AttributeType::ValidationLevel,
    AttributeType::ValidationModuleId,
    AttributeType::ValidationFlag,
    AttributeType::ValidationAuthorityType,
    AttributeType::ValidationCountry,
    AttributeType::ValidationCertificateIdentifier,
    AttributeType::ValidationCertificateUri,
    AttributeType::ValidationVendorUri,
    AttributeType::ValidationProfile,
    AttributeType::Value,
    AttributeType::ValueLen,
    AttributeType::Verify,
    AttributeType::VerifyRecover,
    AttributeType::Wrap,
    AttributeType::WrapWithTrusted,
];

pub struct SigningRequest {
    pub package_file: String,
    pub key_name: String,
    pub slot: String,
}

impl From<&ArgMatches> for SigningRequest {
    fn from(args: &ArgMatches) -> Self {
        Self {
            package_file: args.get_one::<String>("file").unwrap().to_owned(),
            key_name: args.get_one::<String>("keyname").unwrap().to_owned(),
            slot: args.get_one::<String>("slot").unwrap().to_owned()
        }
    }
}